#!/usr/bin/env node
// Writes brand.json (the single source of product naming) into configs and
// generated constants. Run automatically by `npm run dev/build/app:*`.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const brand = JSON.parse(readFileSync(join(root, "brand.json"), "utf8"));
const required = ["productName", "shortName", "bundleId", "dataDirName", "handoffDirName", "cliName"];
for (const k of required) {
  if (typeof brand[k] !== "string" || !brand[k].trim()) {
    console.error(`brand.json: missing "${k}"`);
    process.exit(1);
  }
}
brand.tagline ??= "";

let changed = 0;
function write(rel, content) {
  const p = join(root, rel);
  if (existsSync(p) && readFileSync(p, "utf8") === content) return;
  writeFileSync(p, content);
  changed++;
  console.log(`apply-brand: wrote ${rel}`);
}
function editJson(rel, fn) {
  const p = join(root, rel);
  if (!existsSync(p)) return;
  const obj = JSON.parse(readFileSync(p, "utf8"));
  fn(obj);
  write(rel, JSON.stringify(obj, null, 2) + "\n");
}

const header = "// GENERATED by scripts/apply-brand.mjs from brand.json. Do not edit.\n";
const rs = (s) => JSON.stringify(s);

write(
  "src-tauri/src/brand.rs",
  header +
    `pub const PRODUCT_NAME: &str = ${rs(brand.productName)};\n` +
    `pub const SHORT_NAME: &str = ${rs(brand.shortName)};\n` +
    `pub const BUNDLE_ID: &str = ${rs(brand.bundleId)};\n` +
    `pub const DATA_DIR_NAME: &str = ${rs(brand.dataDirName)};\n` +
    `pub const HANDOFF_DIR_NAME: &str = ${rs(brand.handoffDirName)};\n` +
    `pub const CLI_NAME: &str = ${rs(brand.cliName)};\n` +
    `pub const TAGLINE: &str = ${rs(brand.tagline)};\n`,
);

write(
  "src/brand.ts",
  header +
    `export const brand = ${JSON.stringify(
      {
        productName: brand.productName,
        shortName: brand.shortName,
        bundleId: brand.bundleId,
        dataDirName: brand.dataDirName,
        handoffDirName: brand.handoffDirName,
        cliName: brand.cliName,
        tagline: brand.tagline,
      },
      null,
      2,
    )} as const;\n`,
);

editJson("src-tauri/tauri.conf.json", (c) => {
  c.productName = brand.productName;
  c.identifier = brand.bundleId;
  for (const w of c.app?.windows ?? []) w.title = brand.productName;
});

editJson("package.json", (p) => {
  p.name = brand.dataDirName.toLowerCase().replace(/[^a-z0-9-]/g, "-");
});

const html = join(root, "index.html");
if (existsSync(html)) {
  const src = readFileSync(html, "utf8");
  const esc = brand.productName.replace(/&/g, "&amp;").replace(/</g, "&lt;");
  write("index.html", src.replace(/<title>[^<]*<\/title>/, `<title>${esc}</title>`));
}

if (!changed) console.log("apply-brand: up to date");
