// GENERATED by scripts/apply-brand.mjs from brand.json. Do not edit.
pub const PRODUCT_NAME: &str = "Hybrid Agent Orchestrator";
pub const SHORT_NAME: &str = "Orchestrator";
pub const BUNDLE_ID: &str = "dev.orchestrator.app";
pub const DATA_DIR_NAME: &str = "orchestrator";
pub const HANDOFF_DIR_NAME: &str = ".orchestrator";
pub const CLI_NAME: &str = "orch";
pub const TAGLINE: &str = "Paid agents think. Open-source agents do the rest.";
