// GENERATED by scripts/apply-brand.mjs from brand.json. Do not edit.
export const brand = {
  "productName": "Hybrid Agent Orchestrator",
  "shortName": "Orchestrator",
  "bundleId": "dev.orchestrator.app",
  "dataDirName": "orchestrator",
  "handoffDirName": ".orchestrator",
  "cliName": "orch",
  "tagline": "Paid agents think. Open-source agents do the rest."
} as const;
